version: "3"
services:
  apollo-configservice:
    container_name: apollo-configservice
    build: apollo-configservice/
    image: apollo-configservice
    ports:
      - 8080:8080
    volumes:
      - "${APOLLO_LOGS_DIR}/100003171:/opt/logs/100003171"
    environment:
      - spring_datasource_url=jdbc:mysql://${DB_HOST}:3306/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=${DB_USER}
      - spring_datasource_password=${DB_PASSWORD}
      - eureka.instance.ip-address=${EUREKA_HOST}

    restart: always
