version: "3"
services:
  apollo-adminservice:
    container_name: apollo-adminservice
    build: apollo-adminservice/
    image: apollo-adminservice
    ports:
      - 8090:8090
    volumes:
      - "${APOLLO_LOGS_DIR}/100003172:/opt/logs/100003172"
    environment:
      - spring_datasource_url=jdbc:mysql://${DB_HOST}:3306/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=${DB_USER}
      - spring_datasource_password=${DB_PASSWORD}
      - eureka.instance.ip-address=${EUREKA_HOST}
    restart: always
